export const SERVICE_CATEGORIES: { group: string; items: string[] }[] = [
  {
    group: "Laboratory Tests",
    items: [
      "Hematology",
      "Clinical Chemistry",
      "Molecular Biology",
      "Microbiology & Culture",
      "Immunology & Serology",
      "Histopathology",
      "Cytology",
      "Parasitology",
      "Toxicology",
      "Blood Bank & Transfusion",
      "Point-of-Care Testing",
      "Urinalysis",
      "Endocrinology",
      "Genetic Testing",
      "Drug Monitoring",
    ],
  },
  {
    group: "Imaging & Radiology",
    items: [
      "Ultrasound",
      "X-Ray",
      "CT Scan",
      "MRI",
      "Chest X-Ray",
      "PET Scan",
      "Mammography",
      "Fluoroscopy",
      "DEXA Scan",
      "Echocardiography",
      "Doppler Ultrasound",
      "Interventional Radiology",
    ],
  },
];

export const LAB_CERTIFICATIONS: string[] = [
  "MLSCN Registered",
  "NAFDAC Certified",
  "ISO 15189",
  "ISO 9001",
  "CAP Accredited",
  "WHO Pre-qualified",
  "SON Certified",
  "JCI Accredited",
  "NINAS Accredited",
  "NISAS Accredited",
  "NNQAS Certified",
  "Federal Ministry of Health Approved",
  "State Ministry of Health Approved",
];
