// Nigerian banks with their Paystack bank codes
// Source: Paystack GET /bank (filtered for active Nigerian banks)
export interface NigerianBank {
  name: string;
  code: string;
}

export const NIGERIAN_BANKS: NigerianBank[] = [
  { name: "Access Bank", code: "044" },
  { name: "Access Bank (Diamond)", code: "063" },
  { name: "Carbon (One Finance)", code: "565" },
  { name: "CEMCS Microfinance Bank", code: "50823" },
  { name: "Citibank Nigeria", code: "023" },
  { name: "Ecobank Nigeria", code: "050" },
  { name: "Ekondo Microfinance Bank", code: "562" },
  { name: "Eyowo", code: "50126" },
  { name: "Fidelity Bank", code: "070" },
  { name: "First Bank of Nigeria", code: "011" },
  { name: "First City Monument Bank (FCMB)", code: "214" },
  { name: "Globus Bank", code: "00103" },
  { name: "GoMoney", code: "100022" },
  { name: "Guaranty Trust Bank (GTBank)", code: "058" },
  { name: "Hackman Microfinance Bank", code: "51251" },
  { name: "Heritage Bank", code: "030" },
  { name: "Ibile Microfinance Bank", code: "51244" },
  { name: "Infinity Microfinance Bank", code: "50457" },
  { name: "Jaiz Bank", code: "301" },
  { name: "Keystone Bank", code: "082" },
  { name: "Kuda Bank", code: "50211" },
  { name: "Lagos Building Investment Company (LBIC)", code: "90052" },
  { name: "Links Microfinance Bank", code: "50549" },
  { name: "Lotus Bank", code: "303" },
  { name: "Mayfair Microfinance Bank", code: "50563" },
  { name: "Mint Finex MFB", code: "50304" },
  { name: "Moniepoint Microfinance Bank", code: "50515" },
  { name: "Opay (OPay Digital Services)", code: "100004" },
  { name: "Paga", code: "100002" },
  { name: "PalmPay", code: "100033" },
  { name: "Parallex Bank", code: "526" },
  { name: "Paycom (Opay)", code: "999992" },
  { name: "Polaris Bank", code: "076" },
  { name: "Providus Bank", code: "101" },
  { name: "Rubies Microfinance Bank", code: "125" },
  { name: "Sparkle Microfinance Bank", code: "51310" },
  { name: "Stanbic IBTC Bank", code: "221" },
  { name: "Standard Chartered Bank", code: "068" },
  { name: "Sterling Bank", code: "232" },
  { name: "Suntrust Bank", code: "100" },
  { name: "TAJ Bank", code: "302" },
  { name: "Titan Trust Bank", code: "102" },
  { name: "Union Bank of Nigeria", code: "032" },
  { name: "United Bank for Africa (UBA)", code: "033" },
  { name: "Unity Bank", code: "215" },
  { name: "VFD Microfinance Bank", code: "566" },
  { name: "Wema Bank", code: "035" },
  { name: "Zenith Bank", code: "057" },
];
